version: "3.8"

services:
  mysql-server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=user
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"

  myredis:
    image: redis:6.2
    ports:
      - "6379:6379"